

public class Main
{

     public static void main(String[] args) 
  {
        double x = -17.5;
        System.out.println("As an example, this will give you the absolute value of -17.5: " + Math.abs(x));
        System.out.println("Ceil: " + Math.ceil(x));
        System.out.println("-17.5 to 5th power!: " + Math.pow(x, 5));
        /*
        
        These math formulas are built-in. No need to create an object!.
        These are the most common ones.
        More here: https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html
        
        
        Math.abs(a) gives absolute value
        Math.ceil(a) rounds up the num
        Math.floor(a) rounds down the num
        Math.max(a,b) compares and give the max value
        Math.min(a,b) compares and give the min value
        Math.pow(base,toThePower) ex: 5 to 10th power. Pow stands for power
        Math.sqrt(a);
        */
  }

    
}